### ISSUE TITLE
Can i jump in the same page when i click TOC menu?

### ISSUE THREAD

**Issue by EasterFan** [t9md/atom-markdown-toc-auto#11]
when it is a long markdown file, and it generates a TOC menu, can i jump to the title in the same page by click TOC menu ?

i'm afraid i didn't use it correctly, as the TOC generate a id like (#-2),just like [this](https://github.com/EasterFan/tempic/blob/master/img/atom-toc.png)   
maybe it meets some trouble when it meets Chinese character?  
Or is there anything should i do?  
Thank you very very much!

**Comment by t9md** [comment]
Not having such feature, and no plan.

You should be able to select and jump to markdown header section by `symbols view: toggle file symbols`(cmd-r in macOS)

**Comment by EasterFan** [comment]
That's works! Thank you for replying ! :smile:
