### ISSUE TITLE
Extra line-break

### ISSUE THREAD

**Issue by aw-west** [t9md/atom-markdown-toc-auto#23]
### Praise
Firstly, this is the best markdown TOC package, fast reliable and simple.  Thank you for your work.

### Extra line-break
I was wondering if the second line-break before the end was intended.
```
<!-- TOC START -->
- headings

<!-- TOC END -->
```
It annoys me when writing, so I deleted it.  In `lib\utils.js` line 136 delete the last `\n`
> 136  `toc += buildTocText(editor, scanHeaders(editor), options) + '\n\n'`

### Feature Request: Title
Also, I like titles and currently use `> # TOC` as a title.  How would you implement that as an automated thing?
```
<!-- TOC START title:true -->
> # Table of Contents
- headings
<!-- TOC END -->
```

**Comment by aw-west** [comment]
I solved my feature request using the CoffeeScript implementation of toc.  [Titled Pull Request](https://github.com/nok/markdown-toc/pull/112)

**Comment by aw-west** [comment]
I solved my feature request using the CoffeeScript implementation of toc.  [Titled Pull Request](https://github.com/nok/markdown-toc/pull/112)

**Comment by t9md** [comment]
Fixed now.
I just didn't notice, or maybe I have forgotten to revisit after I skim this issue.
