### ISSUE TITLE
Want to change the unordered list to be asterisk

### ISSUE THREAD

**Issue by datalater** [t9md/atom-markdown-toc-auto#24]
As the current version, TOC generator uses hyphen(-) for unordered list.
But I want to use the asterisk(*) for keeping my markdown style.

Where can I change the setting?

And thanks so much for what you've done. 
Brilliant job 👍

**Comment by aw-west** [comment]
I suggest using `https://github.com/nok/markdown-toc` for numbered lists.

**Comment by t9md** [comment]
@datalater Added new `asterisk` options for both default config on setting-view and text-inlined option.
Try the latest v0.13 I've just released.
