### ISSUE TITLE
markdown-toc-auto usage question

### ISSUE THREAD

**Issue by ronbackman** [t9md/atom-markdown-toc-auto#5]
I have Markdown-toc-auto package installed in my Atom editor.  It seems to create the Table of Contents OK but I am not sure how to make these TOC clickable entries to actually go to the proper location the document.  The resultant Preview display of the TOC appears to be clickable but goes nowhere.

example is this. 

  - [Networking (TCP/IP)](#networking-tcpip)
  - [Linux Flavors](#linux-flavors)

 Those entries are apparently derived from the Headers in the documents.  But when I click on the link in the Atom Preview Mode, the editor does NOT go to the appropriate Header in the text document..  What am I missing?

**Comment by t9md** [comment]
The generated link is to jump when it is displaued on github wiki.
For this purpose, it is working good.
But markdown preview mode it seems not working.

I think you can search issue jn markdown-preview package?  I have. no answer.

**Comment by t9md** [comment]
In my opinion, markdown-preview has to support link within page first.
Nothing I can do in this package, reopen if you think I'm misunderstanding something.
