### ISSUE TITLE
Same header text leads to same link, unlike GitHub’s Markdown renderer

### ISSUE THREAD

**Issue by fasiha** [t9md/atom-markdown-toc-auto#6]
Consider:
```
# Problems

## Base64
### Haskell
### Rust

## XOR key
### Rust
### Octave
### Haskell
```
GitHub.com will give the first pair of “Rust” and “Haskell” headings `#rust` and `#haskell` IDs, and the second set will get IDs `#rust-1` and `#haskell-1`. Neither this package nor the `markdown-toc`package match GitHub.com’s style.

**Comment by t9md** [comment]
Released v0.6.0.
